[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.3"

# SPA fallback (Netlify also respects public/_redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
